//#include <", Subfolders, Keep modified files open, Find Results 1, "Current Project"
#include "myCommon.h"
#include <stdarg.h>
#include <string>
#include <vector>
#include <t3dCommon.h>
#include <t3dlib1.h>
#include <t3dlib2.h>
#include <t3dlib3.h>
#include <t3dlib6.h>
#include <list>
#include <boost/shared_array.hpp>
#pragma push_macro("min")
#pragma push_macro("max")
#define min std::min
#define max std::max
#include <atlimage.h>
#pragma pop_macro("max")
#pragma pop_macro("min")
#include <boost/shared_ptr.hpp>
#include <t3dlib4.h>
#include <cmath>
#include <list>
#include <vector>
#include <boost/shared_ptr.hpp>
#include <boost/shared_array.hpp>
#include <t3dlib3.h>
#include <cstdio>
#include <cassert>
#include <list>
#include <boost/shared_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <t3dlib7.h>
#include <map>
#include <t3dlib1.h>
#include <t3dlib2.h>
#include <t3dlib6.h>
#include <map>
#include <deque>
#include <stack>
#include <boost/shared_ptr.hpp>
#include <cassert>
#include <string>
#include <vector>
#include <map>
#include <Windows.h>
#include <boost/shared_ptr.hpp>
#include <cstdio>
#include <cassert>
#include <crtdbg.h>
#include <boost/scoped_ptr.hpp>
#include <boost/scoped_array.hpp>
#include <cmath>
#include <iostream>
#include <crtdbg.h>
//#include <boost/program_options.hpp>
#include <sstream>
#include <mmsystem.h>
#include <tinyxml.h>
#include <tinyxml.h>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <crtdbg.h>
//  Matching lines: 56    Matching files: 18    Total files searched: 26
